package com.example.klockapp.enums;

public enum AuditOption {
    CLOCK_IN_SUCCESS,
    CLOCK_OUT_SUCCESS,
    SUSPICIOUS_CLOCK_OUT,
    DIFFERENT_DEVICE_DETECT,
    AMBIGUOUS_CLOCK_EVENT,
    LOGIN_SUCCESS,
    USER_CREATED,
    USER_UPDATED,
    DEVICE_ID_RESET,
    PASSWORD_RESET,
    BRANCH_INFO_UPDATED
}
