spring.application.name=${APP_NAME}

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.jwt.secret.key=${JWT_SECRET_KEY}
app.jwt.access.token.expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
app.jwt.refresh.token.expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

# OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=${GOOGLE_OAUTH_SCOPE}

# Cloudinary Configuration
app.cloudinary.api.key=${CLOUDINARY_API_KEY}
app.cloudinary.api.secret=${CLOUDINARY_API_SECRET}
app.cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}

# User Default Profile Picture
app.user.default.picture=${DEFAULT_PROFILE_PICTURE}

# Header Configuration
spring.servlet.multipart.max-file-size=${MAX_SIZE_FILE}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE}

# SpringBoot DevTools
spring.devtools.restart.enabled=${SPRING_BOOT_DEV_TOOLS}

# Tell Tomcat NOT to persist sessions to disk
server.servlet.session.persistent=false

# Super Admin Configuration
app.super.admin.email=${SUPER_ADMIN_EMAIL}
app.super.admin.password=${SUPER_ADMIN_PASSWORD}
app.super.admin.first-name=${SUPER_ADMIN_FIRST_NAME}
app.super.admin.last-name=${SUPER_ADMIN_LAST_NAME}
app.user.admin.phone=${SUPER_ADMIN_PHONE}

# For Spring Boot 3.x / Spring Security 6
server.servlet.session.cookie.same-site=${COOKIE_SAME_SITE}
server.servlet.session.cookie.secure=${COOKIE_SECURE}

# Cors Configuration
app.allowed.origin.patterns=${ALLOWED_ORIGIN_PATTERNS}